stages/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

# Modèle User avec un champ user_type pour distinguer les types d'utilisateurs
class UserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('student', 'Etudiant'),
        ('recruiter', 'Recruteur'),
        ('service_stage', 'Service Stage'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)

    def save(self, *args, **kwargs):
        if not self.user_type:
            raise ValueError("Le type d'utilisateur doit être spécifié.")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username} - {self.user_type}"


# Modèle pour les entreprises (recruteurs)
class Entreprise(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,  # Permet d'ajouter temporairement des valeurs nulles
        blank=True,  # Autorise le champ vide dans les formulaires
    )
    logo = models.ImageField(upload_to='logos/', default='logos/default_logo.png', blank=True, null=True)
    nom = models.CharField(max_length=200)
    created = models.DateField(blank=True, null=True)
    siege = models.CharField(max_length=200, blank=True, null=True)
    adresse = models.CharField(max_length=300, blank=True)
    description = RichTextField(blank=True)
    secteur_activite = models.CharField(max_length=300, blank=True)
    email_contact = models.EmailField(blank=True)

    def __str__(self):
        return self.nom

def validate_pdf(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError("Seuls les fichiers PDF sont autorisés.")

# Modèle pour les étudiants
class Etudiant(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,  # Permet d'ajouter temporairement des valeurs nulles
        blank=True,  # Autorise le champ vide dans les formulaires
        related_name='etudiant',
    )
    photo = models.ImageField(upload_to='media/photos', blank=True, null=True)
    telephone = models.CharField(max_length=15, blank=True)
    date_de_naissance = models.DateField(null=True, blank=True)
    adresse = models.CharField(max_length=200, null=True, blank=True)
    # Nouveaux champs pour les documents
    lettre_motivation = models.FileField(upload_to='etudiants/lettres_motivation/', blank=True, null=True)

    def __str__(self):
        return self.user.username

class CV(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cv')
    fichier = models.FileField(upload_to='etudiants/cv/', blank=True, null=True)
    date_upload = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.fichier.name}"


# Informations académiques
class Formation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="formations")
    titre = models.CharField(max_length=100, blank=True, null=True)
    diplome = models.CharField(max_length=200, blank=True)
    etablissement = models.CharField(max_length=255, blank=True)
    siege_etablissement = models.CharField(max_length=255, blank=True)
    pays_etablissement = models.CharField(max_length=255, blank=True)
    date_inscription = models.DateField(null=True, blank=True)
    date_fin = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.titre

class Competence(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="competences")
    nom = models.CharField(max_length=100)
    niveau = models.CharField(max_length=50, choices=[("Débutant", "Débutant"),
                                                      ("Intermédiaire", "Intermédiaire"),
                                                      ("Avancé", "Avancé"),
                                                      ("Expert", "Expert")])
    date_acquisition = models.DateField(null=True, blank=True)  # Si tu veux suivre la date d'acquisition
    description = RichTextField(blank=True, null=True)  # Une petite description optionnelle

    def __str__(self):
        return f"{self.nom} ({self.niveau})"


class ExperienceProfessionnelle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="experiences_professionnelles")
    poste = models.CharField(max_length=100)
    entreprise = models.CharField(max_length=150)
    departement = models.CharField(max_length=255, null=True, blank=True)
    date_debut = models.DateField()
    date_fin = models.DateField(null=True, blank=True)
    siege_entreprise = models.CharField(max_length=255, blank=True)
    pays_entreprise = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"{self.poste} ({self.entreprise})"

class Entretien(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="entretiens")
    entreprise = models.CharField(max_length=150)
    date = models.DateField()
    statut = models.CharField(max_length=50, choices=[("Prévu", "Prévu"), ("Passé", "Passé"), ("Annulé", "Annulé")])

    def __str__(self):
        return f"{self.entreprise} - {self.statut}"



class ServiceStage(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,  # Permet d'ajouter temporairement des valeurs nulles
        blank=True,  # Autorise le champ vide dans les formulaires
    )
    responsable = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"Service Stage - {self.user}"

# Modèle pour les offres de stage
class OffreStage(models.Model):
    TYPE_STAGE_CHOICES = (
        ('plein', 'Temps plein'),
        ('partiel', 'Temps partiel'),
    )
    titre = models.CharField(max_length=200)
    description = RichTextField()
    type_stage = models.CharField(max_length=200, choices=TYPE_STAGE_CHOICES)
    localisation = models.CharField(max_length=200)
    duree = models.IntegerField()
    date_publication = models.DateTimeField(auto_now_add=True)
    date_limite_postulation = models.DateField()
    entreprise = models.ForeignKey(Entreprise, on_delete=models.CASCADE)

    def __str__(self):
        return self.titre

class Candidature(models.Model):
    STATUT_CHOICES = [
        ('en_attente', 'En attente'),
        ('selectionne', 'Accepté'),
        ('rejete', 'Rejeté'),
    ]
    etudiant = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    offre = models.ForeignKey(OffreStage, on_delete=models.CASCADE, related_name="candidatures")
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, blank=True)
    lettre_motivation = models.FileField(upload_to='lettres_motivation/', blank=True)
    statut = models.CharField(max_length=20, choices=STATUT_CHOICES, default='en_attente')
    commentaires = models.TextField(null=True, blank=True)
    date_soumission = models.DateField(auto_now_add=True)
    date_reponse = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.etudiant.username} - {self.offre.titre}'



class Contrat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="contrats", null=True, blank=True)
    type_contrat = models.CharField(max_length=200)
    poste = models.CharField(max_length=100, null=True, blank=True)
    date_debut = models.DateField()
    date_fin = models.DateField()
    entreprise = models.ForeignKey(Entreprise, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.entreprise} - {self.poste}"




# Signal pour créer le profil en fonction du type d'utilisateur
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         # Créer un profil générique pour chaque utilisateur
#         user_profile = UserProfile.objects.create(user=instance)
#         # Créer des profils spécifiques selon le type d'utilisateur
#         if user_profile.user_type =='student':
#             Etudiant.objects.create(user=instance)
#         elif user_profile.user_type =='recruiter':
#             Entreprise.objects.create(user=instance)
#         elif user_profile.user_type =='service_stage':
#             ServiceStage.objects.create(user=instance)
#
#
#
# # Signal pour sauvegarder le profil après la création ou modification de l'utilisateur
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     try:
#         instance.profile.save()
#     except UserProfile.DoesNotExist:
#         # Si le profil n'existe pas, on peut créer un profil par défaut ou prendre une autre action.
#         user_profile = UserProfile.objects.create(user=instance)
#         user_profile.save()

templates/recruteur/accueil.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}
    <div class="row">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="alert alert-{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <!-- Informations de l'entreprise -->
        <div class="col-md-6 mb-4">
            <a href="{% url 'informations_entreprise' %}" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-building fa-3x mb-3 text-primary"></i>
                        <h5 class="card-title">Informations de l'entreprise</h5>
                        <p>Renseignez ou modifiez les informations de votre entreprise</p>
                    </div>
                </div>
            </a>
        </div>
        <!-- Mes offres -->
        <div class="col-md-6 mb-4">
            <a href="{% url 'mes_offres' %}" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-briefcase fa-3x mb-3 text-success"></i>
                        <h5 class="card-title">Mes offres de stage</h5>
                        <p>Consultez et gérez vos offres de stage</p>
                    </div>
                </div>
            </a>
        </div>
        <!-- Candidatures reçues -->
        <div class="col-md-6 mb-4">
            <a href="{% url 'candidatures_recues' %}" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-users fa-3x mb-3 text-warning"></i>
                        <h5 class="card-title">Candidatures reçues</h5>
                        <p>Consultez les candidatures reçues pour vos offres</p>
                    </div>
                </div>
            </a>
        </div>
        <!-- Gestion des contrats -->
        <div class="col-md-6 mb-4">
            <a href="{% url 'contrats' %}" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-file-signature fa-3x mb-3 text-success"></i>
                        <h5 class="card-title">Contrats</h5>
                        <p>Consultez et gérez vos contrats de stage</p>
                    </div>
                </div>
            </a>
        </div>
        
    </div>
{% endblock %}

<!-- Créer une offre -->
        <div class="col-md-6 mb-4">
            <a href="#" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-plus-circle fa-3x mb-3 text-info"></i>
                        <h5 class="card-title">Créer une offre de stage</h5>
                        <p>Publiez une nouvelle offre de stage</p>
                    </div>
                </div>
            </a>
        </div>

<!-- Statistiques des offres -->
        <div class="col-md-6 mb-4">
            <a href="#" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-chart-line fa-3x mb-3 text-secondary"></i>
                        <h5 class="card-title">Statistiques</h5>
                        <p>Suivez les performances de vos offres de stage</p>
                    </div>
                </div>
            </a>
        </div>

<!-- Messagerie -->
        <div class="col-md-6 mb-4">
            <a href="#" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-comments fa-3x mb-3 text-primary"></i>
                        <h5 class="card-title">Messagerie</h5>
                        <p>Communiquez avec les candidats et étudiants</p>
                    </div>
                </div>
            </a>
        </div>
        <!-- Paramètres du recruteur -->
        <div class="col-md-6 mb-4">
            <a href="#" class="text-decoration-none text-dark">
                <div class="card shadow-sm h-100">
                    <div class="card-body">
                        <i class="fas fa-cogs fa-3x mb-3 text-danger"></i>
                        <h5 class="card-title">Paramètres du profil</h5>
                        <p>Modifiez les informations et préférences de votre compte</p>
                    </div>
                </div>
            </a>
        </div>


    <br>
    <h1 class="display-6 mb-2 text-primary text-center">LISTE DE VOS OFFRES DE STAGES</h1>
    <div class="container mt-4">
        <div class="row">
            {% for offre in offres %}
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ offre.titre }}</h5>
                        <p class="card-text">{{ offre.description|truncatewords:20 }}</p>
                        <a href="{% url 'offre_detail' offre.id %}" class="btn btn-primary">Voir l'offre</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12">
                <p>Aucune offre de stage disponible pour le moment.</p>
            </div>
            {% endfor %}
        </div>
    </div>

templates/recruteur/candidatures_detail.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}
    <style>
    #pdf-preview {
        width: 100%; /* Largeur totale */
        height: 600px; /* Hauteur fixe */
        border: 1px solid #ccc; /* Bordure pour une meilleure visibilité */
        overflow-y: scroll; /* Ajout d'une barre de défilement verticale */
        overflow-x: auto; /* Ajout d'une barre de défilement horizontale si nécessaire */
        padding: 10px; /* Espace autour du contenu */
        box-sizing: border-box; /* Inclure le padding dans les dimensions */
        background: #f9f9f9; /* Couleur de fond pour un contraste visuel */
    }

    canvas {
        display: block;
        margin: 10px auto; /* Centrer les pages du PDF */
    }
</style>
<div class="container">
    <div class="card shadow-sm p-4 mb-4">
        <h1 class="text-center text-uppercase">Détails de la candidature</h1>
        <div class="row align-items-center">
            <h2 class="text-center">Informations sur l'étudiant</h2>
            <div class="col-md-12 d-flex justify-content-between">
                <p><strong>Nom complet :</strong><br> {{ candidature.etudiant.get_full_name }}</p>
                <p><strong>Email :</strong><br> {{ candidature.etudiant.email }}</p>
                <p><strong>Téléphone :</strong><br> {{ candidature.etudiant.etudiant.telephone }}</p>
                <p><strong>Adresse :</strong><br> {{ candidature.etudiant.etudiant.adresse }}</p>
            </div>
        </div>
        <p><strong>CV :</strong>
            {% if cv and cv.fichier %}
                <div class="card shadow-sm mb-4">
                    <div id="pdf-preview" style="width: 100%; height: 600px; border: 1px solid #ccc;"></div>
                    <div class="card-body d-flex justify-content-between mt-3">
                        <a href="{{ cv.fichier.url }}" download class="btn btn-primary">Télécharger</a>
                    </div>
                </div>
            {% else %}
                <span>Aucun CV disponible.</span>
            {% endif %}
        </p>
    </div>
</div>
    
    <!-- En-tête de l'entreprise -->
    <div class="card shadow-sm p-4 mb-4">
        <div class="row align-items-center">
            <h2 class="text-center">Informations sur l'offre</h2>
            <div class="col-md-2">
                <img src="{{ candidature.offre.entreprise.logo.url }}" class="img-fluid">
            </div>
            <div class="col-md-10 d-flex justify-content-between">
                <div>
                    <h1 class="text-black">{{ candidature.offre.titre }}</h1>
                    <p><strong>Type de stage : </strong>{{ candidature.offre.type_stage }}</p>
                    <p><strong>Lieu : </strong>{{ candidature.offre.localisation }}</p>
                    <p><strong>Date de soumission : </strong>{{ candidature.date_soumission }}</p>
                    <p><strong>Statut : </strong>{{ candidature.date_soumission }}</p>
                </div>
                <div class="mt-3">
                    <span class="badge {% if candidature.statut == 'selectionne' %}bg-success{% elif candidature.statut == 'rejete' %}bg-danger{% else %}bg-warning{% endif %}">
                        {{ candidature.get_statut_display }}
                    </span>
                </div>
        </div>
    </div>
</div>
    
    <script>
    document.addEventListener('DOMContentLoaded', () => {
        const pdfUrl = "{{ cv.fichier.url|escapejs }}"; // Remplacez par l'URL de votre fichier PDF

        const renderPDF = async (url, containerId) => {
            const container = document.getElementById(containerId);

            if (!container) {
                console.error("Container not found!");
                return;
            }

            // Charge le document PDF
            const pdf = await pdfjsLib.getDocument(url).promise;

            // Parcourt chaque page et l'ajoute à l'aperçu
            for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber++) {
                const page = await pdf.getPage(pageNumber);

                // Crée un élément canvas pour afficher la page
                const canvas = document.createElement("canvas");
                const context = canvas.getContext("2d");

                const viewport = page.getViewport({ scale: 1.5 });
                canvas.width = viewport.width;
                canvas.height = viewport.height;

                await page.render({ canvasContext: context, viewport: viewport }).promise;

                // Ajoute le canvas à la zone de prévisualisation
                container.appendChild(canvas);
            }
        };

        // Appelez la fonction avec l'URL de votre PDF
        renderPDF(pdfUrl, "pdf-preview");
    });
</script>
{% endblock %}

templates/recruteur/candidatures_recues.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}
  <div class="container">
    <h1>Liste des candidatures reçues</h1>

    <!-- Tableau des candidatures -->
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Nom de l'étudiant</th>
          <th>Offre</th>
          <th>Statut</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for candidature in candidatures %}
          <tr>
            <td>{{ candidature.etudiant.get_full_name }}</td>
            <td>{{ candidature.offre.titre }}</td>
            <td>
              <!-- Affichage du statut -->
              <span class="badge {% if candidature.statut == 'selectionne' %}bg-success{% elif candidature.statut == 'rejete' %}bg-danger{% else %}bg-warning{% endif %}">
                {{ candidature.get_statut_display }}
              </span>
            </td>
            <td>
              <div class="d-flex justify-content-around">
                  <!-- Lien pour consulter la candidature -->
              <a href="{% url 'candidatures_detail' candidature.id %}" class="btn btn-info btn-sm"><i class="fas fa-eye fa-2x"></i></a>

              <!-- Bouton Font Awesome pour modifier le statut -->
              <button class="btn btn-sm" id="edit-status-{{ candidature.id }}" data-bs-toggle="dropdown">
                <i class="fas fa-edit fa-2x"></i>
              </button>

              <!-- Menu déroulant pour changer le statut -->
              <div class="dropdown-menu" aria-labelledby="edit-status-{{ candidature.id }}">
                <form method="post" action="{% url 'changer_statut_candidature' candidature.id %}" hx-post="{% url 'changer_statut_candidature' candidature.id %}" hx-target="#status-badge-{{ candidature.id }}" hx-swap="outerHTML">
                  {% csrf_token %}
                  <div class="dropdown-item">
                    <select id="statut" name="statut" class="form-control">
{#                        <option value="en_attente" {% if candidature.statut == "en_attente" %}selected{% endif %}>En attente</option>#}
                        <option value="selectionne" {% if candidature.statut == "selectionne" %}selected{% endif %}>Sélectionné</option>
                        <option value="rejete" {% if candidature.statut == "rejete" %}selected{% endif %}>Rejeté</option>
                    </select>
                  </div>
                  <button type="submit" class="dropdown-item btn btn-primary">Mettre à jour</button>
                </form>
              </div>
              </div>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="4">Aucune candidature reçue pour cette offre.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
{% endblock %}



<h1>Candidatures reçues</h1>
<ul>
    {% for candidature in candidatures %}
    <li>
        <p><strong>Nom du candidat : </strong>{{ candidature.candidat.user.get_full_name }}</p>
        <p><strong>Offre : </strong>{{ candidature.offre.titre }}</p>
        <p><strong>Date : </strong>{{ candidature.date_postule }}</p>
        <a href="{% url 'candidature_detail' candidature.id %}" class="btn btn-info">Voir détails</a>
    </li>
    {% empty %}
    <p>Aucune candidature reçue pour le moment.</p>
    {% endfor %}
</ul>

templates/recruteur/changer_statut_candidature.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}
<div class="container">
    <h1>Changer le statut de la candidature</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="statut">Nouveau statut</label>
            <select id="statut" name="statut" class="form-control">
{#                <option value="en_attente" {% if candidature.statut == "en_attente" %}selected{% endif %}>En attente</option>#}
                <option value="selectionne" {% if candidature.statut == "selectionne" %}selected{% endif %}>Sélectionné</option>
                <option value="rejete" {% if candidature.statut == "rejete" %}selected{% endif %}>Rejeté</option>
            </select>
        </div>
        <button type="submit" class="btn btn-success">Mettre à jour</button>
    </form>
</div>
{% endblock %}

templates/recruteur/contrats.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}

<h1>Contrats signés</h1>
<ul>
    {% for contrat in contrats %}
    <li>
        <p><strong>Nom du stagiaire : </strong>{{ contrat.stagiaire.user.get_full_name }}</p>
        <p><strong>Offre : </strong>{{ contrat.offre.titre }}</p>
        <p><strong>Date de début : </strong>{{ contrat.date_debut }}</p>
        <p><strong>Date de fin : </strong>{{ contrat.date_fin }}</p>
        <a href="{{ contrat.fichier.url }}" class="btn btn-primary">Télécharger le contrat</a>
    </li>
    {% empty %}
    <p>Aucun contrat signé pour le moment.</p>
    {% endfor %}
</ul>
{% endblock %}

templates/recruteur/creer_entreprise.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Créer une entreprise</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
</div>
{% endblock %}

templates/recruteur/entreprise_recruteur_detail.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}
<div class="container">

    <!-- En-tête de l'entreprise -->
    <div class="card shadow-sm p-4 mb-4" style="background: linear-gradient(90deg, #1b5ba7, rgb(47, 179, 68));">
        <div class="row align-items-center">
            <div class="col-md-2">
                <img src="{{ offre.entreprise.get_logo_url }}" alt="Logo de {{ offre.entreprise.nom }}" class="img-fluid">
            </div>
            <div class="col-md-10">
                <h2 class="text-white">{{ entreprise.nom }}</h2>
                <p class="text-white mb-0">
                    <i class="fas fa-map-marker-alt"></i> {{ entreprise.siege }}
                    &nbsp;&nbsp;
                    <i class="fas fa-calendar-alt"></i> {{ entreprise.created|date:"Y" }}
                </p>
                <div class="mt-3">
                    <a href="#" class="btn btn-outline-light">Modifier</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Présentation de l'entreprise -->
    <div class="card mb-4">
        <div class="card-header">
            <h3>Présentation de l'entreprise</h3>
        </div>
        <div class="card-body">
            <p>{{ entreprise.description | safe }}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/recruteur/mes_offres.html
{% extends 'recruteur/base_recruteur.html' %}

{% block content %}
    <section class="container text-center">
        <h1>Vos offres de stages</h1>
        <p class="text-muted">Consultez toutes vos offres</p>
        
        <div class="input-group my-4 w-50 mx-auto">
            <input type="text" class="form-control" placeholder="Chercher">
            <button class="btn btn-dark">Rechercher Opportunité</button>
        </div>
    </section>
    <div class="row">
        {% for offre in offres %}
            <div class="col-md-6 mb-4">
                <a href="{% url 'detail_offre_recruteur' offre.id %}" class="card shadow-sm text-decoration-none">
                    <div class="card-body d-flex align-items-center">
                        <img src="{{ offre.entreprise.logo.url }}" class="img-fluid" style="width: 100px; height: 100px">
                        <div class="flex-grow-1">
                            <h3 class="card-title mb-2">{{ offre.titre }}</h3>
                            <p class="text-muted mb-3">{{ offre.entreprise.nom }}</p>
                            <div class="d-flex gap-3 align-items-center">
                                <span class="badge bg-secondary">
                                    <i class="fas fa-briefcase"></i> Stage fonctionnel
                                </span>
                                <span class="badge bg-secondary">
                                    <i class="fas fa-map-marker-alt"></i> {{ offre.localisation }}
                                </span>
                                <span class="badge bg-secondary">
                                    <i class="fas fa-building"></i> Sur site
                                </span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% empty %}
            <p>Vous n'avez publié aucune offre de stage pour le moment.</p>
        {% endfor %}
    </div>
{% endblock %}

<li>
            <h3>{{ offre.titre }}</h3>
            <p>{{ offre.description | safe }}</p>
            <a href="{% url 'offre_detail' offre.id %}" class="btn btn-info">Voir</a>
            <a href="#" class="btn btn-warning">Modifier</a>
            <a href="#" class="btn btn-danger">Supprimer</a>
        </li>